CryptoTradingPlatform/Models/Trading/TradingFormModel.cs
namespace CryptoTradingPlatform.Models.Trading
{
    public class TradingFormModel
    {
        public string Name { get; init; }

        public double Quantity { get; set; }

        public decimal Price { get; set; }

        public string Type { get; set; }
    }
}

CryptoTradingPlatform/Controllers/TradingController.cs
using CryptoTradingPlatform.Constants;
using CryptoTradingPlatform.Core.Contracts;
using CryptoTradingPlatform.Core.Models.Api;
using CryptoTradingPlatform.Core.Models.Trading;
using CryptoTradingPlatfrom.Core.Contracts;
using CryptoTradingPlatfrom.Core.Models.Assets;
using CryptoTradingPlatfrom.Core.Models.Trading;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.FileProviders;
using System.Text;

namespace CryptoTradingPlatform.Controllers
{
    public class TradingController : BaseController
    {
        private readonly IAssetService assetService;
        private readonly ICryptoApiService cryptoService;
        private readonly ITradingService tradingService;
        public TradingController(IAssetService _assetService, ICryptoApiService _cryptoService, ITradingService _tradingService)
        {
            assetService = _assetService;
            cryptoService = _cryptoService;
            tradingService = _tradingService;
        }

        public async Task<IActionResult> Swap()
        {
            SwapAssetsListViewModel model = await assetService.GetUserAssets(User.Identity.Name);
            ViewBag.UserMoney = model.UserMoney;
            ViewBag.Assets = model.Assets.ToList();

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Swap(BuyAssetFormModel model)
        {
            if (!ModelState.IsValid)
            {
                ViewData[MessageConstants.UnexpectedError] = MessageConstants.UnexpectedError;
                return View(model);
            }

            SwapAssetsListViewModel customModel = await assetService.GetUserAssets(User.Identity.Name);
            ViewBag.UserMoney = customModel.UserMoney;
            ViewBag.Assets = customModel.Assets.ToList();

            decimal buyQuantity = await tradingService.CalculateTransaction(model);
            model.BuyAssetQuantity = buyQuantity;
            ViewData["BuyQuantity"] = Math.Round(buyQuantity, 8);

            if (model.Calculate == "Calculate")
            {
                return View(model);
            }


            bool success = await tradingService.SaveSwap(model, User.Identity.Name);

            if (!success)
            {
                ViewData[MessageConstants.UnexpectedError] = MessageConstants.UnexpectedError;
                return View(model);
            }

            TempData[MessageConstants.Success] = "Swap Successful!";
            return Redirect("/");
        }

        public async Task<IActionResult> Trade()
        {
            List<string> tickers = await assetService.GetAllAssetTickers();
            List<CryptoResponseModel> cryptos = await cryptoService.GetCryptos(tickers);
            SwapAssetsListViewModel customModel = await assetService.GetUserAssets(User.Identity.Name);
            ViewBag.UserMoney = customModel.UserMoney;
            ViewBag.UserAssets = customModel.Assets.ToList();
            ViewBag.Assets = cryptos;

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Trade(TradingFormModel model)
        {
            List<CryptoResponseModel> cryptos = await cryptoService.GetCryptos(new List<string> { model.Ticker });
            model.Price = cryptos[0].Price;

            if (!ModelState.IsValid)
            {
                TempData[MessageConstants.UnexpectedError] = MessageConstants.UnexpectedError;
                return RedirectToAction("Trade");
            }
            bool success = await tradingService.SaveTransaction(model, User.Identity.Name);

            if (!success)
            {
                TempData[MessageConstants.UnexpectedError] = MessageConstants.UnexpectedError;
                return RedirectToAction("Trade");
            }

            TempData[MessageConstants.Success] = "Transaction Successful";
            return Redirect("/");
        }

        public async Task<IActionResult> History(string sortOrder)
        {
            ViewData["DateSortParm"] = sortOrder == "Date" ? "date_desc" : "Date";
            ViewData["NameSortParm"] = sortOrder == "Name" ? "name_desc" : "Name";
            ViewData["TypeSortParm"] = sortOrder == "Type" ? "type_desc" : "Type";
            ViewData["QuantitySortParm"] = sortOrder == "Quantity" ? "quantity_desc" : "Quantity";
            ViewData["PriceSortParm"] = sortOrder == "Price" ? "price_desc" : "Price";
            ViewData["FeeeSortParm"] = sortOrder == "Fee" ? "fee_desc" : "Fee";

            List<TransactionHistoryViewModel> transactions = await tradingService.GetUserTradingHistory(User.Identity.Name);

            transactions = tradingService.SortTransactions(sortOrder, transactions);

            return View(transactions);
        }

        [HttpPost]
        public async Task<ActionResult> AddToFavorites(string ticker)
        {
            bool result = await tradingService.SaveToFavorites(ticker, User.Identity.Name);

            if (!ModelState.IsValid || result == false)
            {
                return Json(new { success = false });
            }

            return Json(new { success = true });
        }

        public async Task<IActionResult> Favorites()
        {
            List<string> tickers = await assetService.GetAllFavoritesTickers(User.Identity.Name);
            if (tickers.Count == 0)
            {
                TempData[MessageConstants.Warning] = "You currently don't have any favorites!";
                return Redirect("/");
            }
            List<CryptoResponseModel> cryptos = await cryptoService.GetCryptos(tickers);

            return View(cryptos);
        }
        public async Task<IActionResult> Download()
        {
            List<TransactionHistoryViewModel> transactions = await tradingService.GetUserTradingHistory(User.Identity.Name);
            StringBuilder sb = new StringBuilder();

            sb.AppendLine("AssetName,Date,Price,Quantity,Type");
            foreach (var item in transactions)
            {
                sb.AppendLine(item.AssetName + ", " + item.Date + ", " + item.Price + ", " + item.Quantity + ", " + item.Type);

            }

            return File(new UTF8Encoding().GetBytes(sb.ToString()), "text/csv", $"{User.Identity.Name}_Trading_History.csv");

        }

    }
}

CryptoTradingPlatform/Views/Trading/Favorites.cshtml
@model List<CryptoResponseModel>
@{
    ViewData["Title"] = "Favorites";
}

<h1 class="text-center">Your Favorite Cryptocurrencies</h1>

 <partial name="_CryptoTable" />

CryptoTradingPlatform/Views/Trading/History.cshtml
@using CryptoTradingPlatfrom.Core.Contracts
@model IEnumerable<TransactionHistoryViewModel>

@inject ITradingService tradingService;

<h1 class="text-center"><i class="fas fa-comment-dollar text-success fa-xs" style="font-size:30px"></i>Transaction History</h1>

<table class="table text-nowrap mt-4 cryptotable">
    <thead>
        <tr>
            <th scope="col">
                <a class="text-white" style="text-decoration:none" asp-action="History" asp-route-sortOrder="@ViewData["NameSortParm"]">@Html.DisplayNameFor(model => model.AssetName)</a>
            </th>
            <th scope="col">
                <a class="text-white" style="text-decoration:none" asp-action="History" asp-route-sortOrder="@ViewData["DateSortParm"]">@Html.DisplayNameFor(model => model.Date)</a>
            </th>
            <th scope="col">
                <a class="text-white" style="text-decoration:none" asp-action="History" asp-route-sortOrder="@ViewData["PriceSortParm"]">@Html.DisplayNameFor(model => model.Price)</a>
            </th>
            <th scope="col">
                <a class="text-white" style="text-decoration:none" asp-action="History" asp-route-sortOrder="@ViewData["QuantitySortParm"]">@Html.DisplayNameFor(model => model.Quantity)</a>
            </th>
            <th scope="col">
                <a class="text-white" style="text-decoration:none" asp-action="History" asp-route-sortOrder="@ViewData["TypeSortParm"]">@Html.DisplayNameFor(model => model.Type)</a>
            </th>
            <th scope="col">
                <a class="text-white" style="text-decoration:none" asp-action="History" asp-route-sortOrder="@ViewData["FeeSortParm"]">@Html.DisplayNameFor(model => model.Fee)</a>
            </th>
        </tr>
    </thead>
    <tbody class="bg-black p-2 text-dark bg-opacity-10 text-white">

        @foreach (var tr in Model)
        {
            <tr>
                <td>
                    @tr.AssetName
                </td>
                <td>
                    @tr.Date
                </td>
                <td>
                    @tr.Price.ToString("C",new CultureInfo("en-US"))
                </td>
                <td>
                    @tr.Quantity
                </td>
                @if (tr.Type == "Buy")
                {
                    <td class="text-danger">
                        @tr.Type
                    </td>
                }
                else if (tr.Type == "Sell")
                {
                    <td class="text-success">
                        @tr.Type
                    </td>
                }
                else if (tr.Type == "Swap")
                {
                    <td class="text-info">
                        @tr.Type
                    </td>
                }
                <td>
                    @tr.Fee.ToString("C",new CultureInfo("en-US"))
                </td>
            </tr>
        }
    <tbody>
</table>
<div class="row mt-3">
    <div class="col">
        <a href="/Trading/Download"><button type="submit" class="btn btn-primary btn-lg btn-block mt-2 rounded-pill">Downloadd History</button></a>
    </div>
</div>

CryptoTradingPlatform/Views/Trading/Swap.cshtml
@using CryptoTradingPlatfrom.Core.Models.Assets
@model BuyAssetFormModel

@{
    var Assets = (List<SwapAssetViewModel>)ViewBag.Assets;
}

<div class="container">
    <h3 class="text-center font-weight-bold">Swap</h3>
    <div class="offset-md-4 col-md-4 col-sm-12">
        <form method="post" asp-controller="Trading" asp-action="Swap">
            <div class="row form-group">
                <div class="col-6">
                    <select asp-for="SellAssetId" class="rounded-pill form-select form-select-lg" aria-label="form-select-lg example">
                        <option class="text-dark" value="" disabled selected>Select a crypto</option>
                        @foreach (var asset in Assets)
                        {
                            <option class="text-dark" value="@asset.AssetId">@asset.AssetName</option>
                        }
                    </select>
                    <div class="ms-2">
                        <span asp-validation-for="SellAssetId" class="small text-danger"></span>
                    </div>
                </div>
                <div class="col-6">
                    <input asp-for="SellAssetQyantity" step="0.001" type="number" class="form-control-lg rounded-pill border-0 text-dark" placeholder="Enter Amount">
                    <div class="ms-2">
                        <span asp-validation-for="SellAssetQyantity" class="small text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="form-group text-center">
                <i class="bi bi-arrow-down-circle-fill bi-xl" style="font-size:30px"></i>
            </div>
            <div class="row form-group">
                <div class="col-6">
                    <select asp-for="BuyAssetId" class="rounded-pill form-select form-select-lg" aria-label="form-select-lg example">
                        <option class="text-dark" value="" disabled selected>Select a crypto</option>
                        @foreach (var asset in Assets)
                        {
                            <option class="text-dark" value="@asset.AssetId">@asset.AssetName</option>
                        }
                    </select>
                    <div class="ms-2">
                        <span asp-validation-for="BuyAssetId" class="small text-danger"></span>
                    </div>
                </div>
                <div class="col-6 text-dark">
                    <input asp-for="@ViewData["BuyQuantity"]" type="text" class="text-dark border-0 form-control-lg rounded-pill" disabled placeholder="Calculating...">
                    <span asp-validation-for="BuyAssetQuantity" class="small text-danger"></span>
                </div>
            </div>
            <div class="row">
                <div class="col text-center">
                    <button type="submit" class="btn btn-success btn-lg btn-block mt-2 rounded-pill">Swap</button>
                </div>
                <div class="col text-center">
                    <p><input asp-for="Calculate" value="Calculate" type="submit" class="btn btn-primary btn-lg btn-block mt-2 rounded-pill" /></p>
                </div>
            </div>
        </form>
    </div>
</div>

CryptoTradingPlatform/Views/Trading/Trade.cshtml
@model TradingFormModel
@{
    ViewData["Title"] = "Trade Now";
    var Assets = (List<CryptoResponseModel>)ViewBag.Assets;
    var UserAssets = (List<SwapAssetViewModel>)ViewBag.UserAssets;

}

<!--CHANGE THIS TO VIEW COMPONENT-->

<div class="container">
    <div class="row">
        <div class="col">
            <div class="card" style="width: 18rem;">
                <img class="card-img-top" src="https://www.w3schools.com/bootstrap4/img_avatar1.png" alt="Card image cap">
                <div class="card-body text-dark">
                    <h5 class="card-title text-dark">@User.Identity.Name</h5>
                    <p class="card-text mb-1 text-dark">Your current account balance is: <p class="text-dark font-weight-bolder">$@ViewBag.UserMoney.ToString("f2")</p></p>
                    @if (UserAssets.Count > 0)
                    {
                        <p class="text-dark">Your current assets: </p>
                        @for (int i = 0; i < @UserAssets.Count; i++)
                        {
                            <div>
                                <img style="float: left;" src=@UserAssets[i].ImageUrl alt="logo" width="16" height="16">
                                <p class="text-dark mb-1">&thinsp; @UserAssets[i].AssetName: @UserAssets[i].AssetQuantity.ToString("f4")</p>
                            </div>
                        }
                    }
                    <div class="row">
                        <a href="/Identity/Account/Manage" class="btn btn-primary mt-2 rounded-pill">Account</a>
                        <a href="/Trading/History" class="btn btn-success mt-2 rounded-pill">Transaction History</a>
                        <a href="/Trading/Favorites" class="btn btn-success mt-2 rounded-pill">Favorites</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="row form-group">
                <table class="table text-nowrap mt-4 cryptotable">
                    <thead>
                        <tr>
                            <th scope="col">Name</th>
                            <th scope="col">Ticker</th>
                            <th scope="col">Supply</th>
                            <th scope="col">Price</th>
                            <th scope="col">Quantity</th>
                            <th scope="col">Buy</th>
                            <th scope="col">Sell</th>
                        </tr>
                    </thead>
                    <!--Use AJAX-->
                    <tbody id="tbody" class="bg-black p-2 text-dark bg-opacity-10 text-white">
                        @foreach (var asset in Assets)
                        {
                            <form method="post" asp-controller="Trading" asp-action="Trade">
                            <tr class="cryptotable">
                                <td>
                                    <picture>
                                        <img src=@asset.Logo alt="logo" width="36" height="36">
                                    </picture>
                                    <label>
                                            @asset.Name
                                        <input type="hidden" asp-for="Name" value="@asset.Name">
                                    </label>
                                </td>
                                <td class="text-muted">
                                    <label>
                                            @asset.Ticker
                                        <input type="hidden" asp-for="Ticker" value="@asset.Ticker">
                                    </label>
                                </td>
                                <td>
                                        @asset.CirculatingSupply.ToString("N0",new CultureInfo("en-US"))
                                </td>
                                <td>
                                    <label>
                                            @asset.Price.ToString("C",new CultureInfo("en-US"))
                                        <input type="hidden" asp-for="Price" value="@asset.Price"> 
                                    </label>
                                </td>
                                <td>
                                    <input asp-for="Quantity" style="width:100%" step="0.0001" type="number" class="rounded-pill text-dark" />
                                </td>
                                <td>
                                    <p><input asp-for="Type" value="Buy" type="submit" class="btn btn-success btn btn-block rounded-pill border-0" /></p>
                                </td>
                                <td>
                                    <p><input asp-for="Type" value="Sell" type="submit" class="btn btn-danger btn btn-block rounded-pill border-0" /></p>
                                </td>
                            </tr>
                            </form>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>