CryptoTradingPlatform/Models/Assets/AddAssetFormModel.cs
using CryptoTradingPlatform.Data;
using System.ComponentModel.DataAnnotations;

namespace CryptoTradingPlatform.Models.Assets
{
    public class AddAssetFormModel
    {

/*        [Required]
        [MaxLength(DataConstants.AssetMaxLength)]
        public string Name { get; set; }
*/
        [Required]
        [MaxLength(DataConstants.TickerMaxLength)]
        public string Ticker { get; set; }
/*
        [Required]
        public string ImageURL { get; set; }

        [Required]
        [MaxLength(DataConstants.CreatorNameMaxLength)]
        [Display(Name = "Creator Name")]
        public string CreatorName { get; set; }

        [Required]
        [Range(1, long.MaxValue)]
        [Display(Name = "Total Sypply")]
        public long TotalSypply { get; set; }

        [Required]
        [MaxLength(DataConstants.DescriptionMaxLength)]
        public string Description { get; set; }*/

    }
}

CryptoTradingPlatform/Controllers/AssetsController.cs
using CryptoTradingPlatform.Constants;
using CryptoTradingPlatform.Core.Contracts;
using CryptoTradingPlatform.Core.Models;
using CryptoTradingPlatform.Core.Models.Api;
using CryptoTradingPlatform.Core.Models.Assets;
using CryptoTradingPlatfrom.Core.Contracts;
using CryptoTradingPlatfrom.Core.Models.Assets;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CryptoTradingPlatform.Controllers
{
    public class AssetsController : BaseController
    {
        private readonly ICryptoApiService cryptoApiService;
        private readonly IAssetService assetService;

        public AssetsController(ICryptoApiService _cryptoApiService, IAssetService _assetService)
        {
            cryptoApiService = _cryptoApiService;
            assetService = _assetService;
        }

        [Authorize(Roles = "Administrator, Manager")]
        public async Task<IActionResult> Add() => View();

        [HttpPost]
        [Authorize(Roles = "Administrator, Manager")]
        public async Task<IActionResult> Add(AddAssetFormModel asset)
        {
            var isNumeric = int.TryParse(asset.Ticker, out int value);

            if (isNumeric)
            {
                ViewData[MessageConstants.UnexpectedError] = "Ticker cannot but a number";
                return View();
            }
            if (!ModelState.IsValid)
            {
                ViewData[MessageConstants.UnexpectedError] = MessageConstants.UnexpectedError;
                return View();
            }

            List<string> assets = new List<string>();
            assets.Add(asset.Ticker);

            Task<List<CryptoResponseModel>> models = cryptoApiService.GetCryptos(assets);

            if (models.Result == null)
            {
                ViewData[MessageConstants.UnexpectedError] = "Ticker is Invalid";
                return View();
            }

            CryptoResponseModel model = models.Result.FirstOrDefault();
            (bool success, string error) = await assetService.AddAsset(model);

            if (!success)
            {
                ViewData[MessageConstants.UnexpectedError] = error;
                return View();
            }

            TempData[MessageConstants.Success] = "Crypto Added!";
            return Redirect("/");
        }

        public async Task<IActionResult> Details(string assetName)
        {
            AssetDetailsViewModel model = await assetService.GetDetails(assetName);
            bool isOwned = await assetService.IsAssetOwned(assetName);
            if (model == null)
            {
                ViewData[MessageConstants.UnexpectedError] = "Asset doesn't exist on the platform";
                return View();
            }
            ViewBag.IsOwned = isOwned;
            return View(model);
        }

        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Remove(string assetName)
        {
            if (string.IsNullOrEmpty(assetName))
            {
                return View();
            }

            bool success = await assetService.RemoveAsset(assetName);

            if (!success)
            {
                TempData[MessageConstants.Warning] = "You can't remove assets, which users currently trade!";
                return RedirectToAction("Index", "Home", new { area = "" });
            }

            TempData[MessageConstants.Success] = "Assst Removed!";
            return Redirect("/");

        }
    }
}

CryptoTradingPlatform/Views/Assets/Add.cshtml
@model AddAssetFormModel

@{
    ViewData["Title"] = "Add Asset";
}



<div class="container text-white">
    <div class="row">
        <div class="offset-md-2 col-md-8 col-sm-12">
            <h1 class="text-center">Add an asset</h1>
            <h2 class="text-center">Create a new asset to be traided on the platform</h2>
            <form method="post">
                <div class="form-group mt-2">
                    <label class="form-label">Ticker - write down the ticker of the asset and we'll do the rest!</label>
                    <input asp-for="Ticker" type="text" class="form-control">
                    <span asp-validation-for="Ticker" class="small text-danger"></span>
                </div>
               @* <div class="form-group mt-2">
                    <label class="form-label mt-2">Name</label>
                    <input asp-for="Name" type="text" class="form-control">
                    <span asp-validation-for="Name" class="small text-danger"></span>
                </div>*@
                @*<div class="form-group mt-2">
                    <label asp-for="CreatorName" class="form-label"></label>
                    <input asp-for="CreatorName" type="text" class="form-control">
                    <span asp-validation-for="CreatorName" class="small text-danger"></span>
                </div>
                <div class="form-group mt-2">
                    <label asp-for="TotalSypply" class="form-label"></label>
                    <input asp-for="TotalSypply" type="text" class="form-control">
                    <span asp-validation-for="TotalSypply" class="small text-danger"></span>
                </div>
                <div class="form-group mt-2">
                    <label class="form-label">Image URL</label>
                    <input asp-for="ImageURL" type="text" class="form-control">
                    <span asp-validation-for="ImageURL" class="small text-danger"></span>
                </div>
                <div class="form-group mt-2">
                    <label class="form-label">Story</label>
                    <textarea asp-for="Description" class="form-control" rows="4"></textarea>
                    <span asp-validation-for="Description" class="small text-danger"></span>
                </div>*@
                <button type="submit" class="btn btn-primary mt-2 rounded-pill">Add</button>
            </form>
        </div>
    </div>
</div>

CryptoTradingPlatform/Views/Assets/Details.cshtml
@model AssetDetailsViewModel


<div class="container">
    <div class="row">
        <div class="col-2 col-sm-1 mt-4">
            <img src="@Model.Logo" alt="@Model.Ticker">
        </div>
        <div class="col-2 col-sm-1 mt-4 text-muted fs-1">
            @Model.Ticker
        </div>
        <div class="col-2 col-md-1 mt-4 fw-bold fs-1">
            @Model.Name
        </div>
    </div>
    <div class="row col-8 mt-3 cryptotable">
        <p>@Model.Description</p>
    </div>
    <a href="/Trading/Trade" class="button btn btn-success mt-2 rounded-pill">Trade now</a>
    @if (User.IsInRole(RolesConstants.Administrator) && ViewBag.IsOwned)
    {
        <a href="/Assets/Remove?assetName=@Model.Name" class="button btn disabled btn-danger mt-2 rounded-pill">Remove</a>
    }
    else if (User.IsInRole(RolesConstants.Administrator))
    {
        <a href="/Assets/Remove?assetName=@Model.Name" class="button btn btn-danger mt-2 rounded-pill">Remove</a>
    }
</div>

CryptoTradingPlatform/Views/Assets/Swap.cshtml
@using CryptoTradingPlatfrom.Core.Models.Assets
@model BuyAssetFormModel

@{
    var Assets = (List<SwapAssetViewModel>)ViewBag.Assets;
}

<div class="container">
    <h3 class="text-center font-weight-bold text-white">Swap</h3>
    <div class="offset-md-4 col-md-4 col-sm-12">
        <form method="post" asp-controller="Assets" asp-action="Swap">
            <div class="row form-group">
                <div class="col-6">
                    <select asp-for="SellAssetId" class="rounded-pill form-select form-select-lg" aria-label="form-select-lg example">
                        <option value="" disabled selected>Select a crypto</option>
                        @foreach (var asset in Assets)
                        {
                            <option value="@asset.AssetId">@asset.AssetName</option>
                        }
                    </select>
                    <div class="ms-2">
                        <span asp-validation-for="SellAssetId" class="small text-danger"></span>
                    </div>
                </div>
                <div class="col-6">
                    <input asp-for="SellAssetQyantity" step="0.001"type="number" class="form-control-lg rounded-pill border-0" placeholder="Enter Amount">
                    <div class="ms-2">
                        <span asp-validation-for="SellAssetQyantity" class="small text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="form-group text-center">
                <i class="bi bi-arrow-down-circle-fill bi-xl" style="font-size:30px"></i>
            </div>
            <div class="row form-group">
                <div class="col-6">
                    <select asp-for="BuyAssetId" class="rounded-pill form-select form-select-lg" aria-label="form-select-lg example">
                        <option value="" disabled selected>Select a crypto</option>
                        @foreach (var asset in Assets)
                        {
                            <option value="@asset.AssetId">@asset.AssetName</option>
                        }
                    </select>
                    <div class="ms-2">
                        <span asp-validation-for="BuyAssetId" class="small text-danger"></span>
                    </div>
                </div>
                <div class="col-6">
                    <input asp-for="@ViewData["BuyQuantity"]" type="text" class="border-0 form-control-lg rounded-pill" disabled placeholder="Calculating...">
                    <span asp-validation-for="BuyAssetQuantity" class="small text-danger"></span>
                </div>
            </div>
            <div class="row">
                <div class="col text-center">
                <button type="submit" class="btn btn-success btn-lg btn-block mt-2 rounded-pill">Swap</button>
            </div>
             <div class="col text-center">
                <p><input asp-for="Calculate" value="Calculate" type="submit" class="btn btn-primary btn-lg btn-block mt-2 rounded-pill"/></p>
            </div>
            </div>
        </form>
    </div>
</div>